apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy1
  labels:
    app: tomcat-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-cd1
  template:
    metadata:
      labels:
        app: tomcat-cd1
    spec:
      containers:
      - name: tomcat-cd1
        image: adityaverticurl/myapp:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
